version: "3.8"

services:
  locust:
    image: pwnintended/locust:latest
    networks:
      - locust
    deploy:
      replicas: 10
      resources:
          limits:
              cpus: '0.1'
              memory: '100M'

networks:
    locust: {}