version: "3.8"

services:
  locust-bootstrap:
    image: pwnintended/locust:latest
    entrypoint: ./locust node --seed "compose_seed_fwefwefwef453453453453453" --port 9000
    networks:
      - locust
    deploy:
      replicas: 1
      resources:
          limits:
              cpus: '0.1'
              memory: '100M'
  locust-peer:
    depends_on:
      - locust-bootstrap
    image: pwnintended/locust:latest
    entrypoint: ./locust node -p /ip4/172.24.0.2/tcp/9000/p2p/12D3KooWBuCo5DrTC9RarS3e6qPX2bEg5yBRZaFppGfC26BPioPV
    networks:
      - locust
    deploy:
      replicas: 10
      resources:
          limits:
              cpus: '0.1'
              memory: '100M'

networks:
    locust: {}